<?xml version="1.0"?>
<robot name="simple_quadrotor" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define reusable variables -->
  <xacro:property name="body_length" value="0.3"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.05"/>
  <xacro:property name="prop_radius" value="0.05"/>
  <xacro:property name="prop_height" value="0.01"/>
  <xacro:property name="arm_offset" value="0.15"/>

  <!-- Main body of the drone -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
  </link>

  <!-- Propellers - placed at each corner -->
  <!-- Front Left -->
  <link name="prop_fl">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 ${prop_height/2}" rpy="0 0 0"/>
      <material name="black">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="joint_fl" type="fixed">
    <parent link="base_link"/>
    <child link="prop_fl"/>
    <origin xyz="${arm_offset} ${arm_offset} ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Front Right -->
  <link name="prop_fr">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 ${prop_height/2}" rpy="0 0 0"/>
      <material name="black"/>
    </visual>
  </link>

  <joint name="joint_fr" type="fixed">
    <parent link="base_link"/>
    <child link="prop_fr"/>
    <origin xyz="-${arm_offset} ${arm_offset} ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Back Left -->
  <link name="prop_bl">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 ${prop_height/2}" rpy="0 0 0"/>
      <material name="black"/>
    </visual>
  </link>

  <joint name="joint_bl" type="fixed">
    <parent link="base_link"/>
    <child link="prop_bl"/>
    <origin xyz="${arm_offset} -${arm_offset} ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Back Right -->
  <link name="prop_br">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 ${prop_height/2}" rpy="0 0 0"/>
      <material name="black"/>
    </visual>
  </link>

  <joint name="joint_br" type="fixed">
    <parent link="base_link"/>
    <child link="prop_br"/>
    <origin xyz="-${arm_offset} -${arm_offset} ${body_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
